config/routes.rb
Rails.application.routes.draw do
  root 'products#home'
  resources :reviews
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :image, :description, presence: true
  validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}
  has_many :reviews, dependent: :destroy

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars).gsub(/(\d)(?=(\d{3})+(?!\d))/, "\\1,")
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :assignments
  has_many :roles, through: :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :destroy, :new, :create]
  # before_filter :authorize

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  def home
    @products = Product.last(3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents, :image)
    end

    def check_if_admin
      unless current_user.is_admin
        redirect_to '/'
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # before_filter :authorize

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def role?(role)
    roles.any? { |r| r.name.underscore.to_sym == role }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>WynShop</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="	http://getbootstrap.com/docs/4.0/examples/carousel/carousel.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
	<%= render "shared/nav" %>
	<div class="container">

			<%= yield %>
	</div>

  <!-- <hr class="featurette-divider">

	<footer class="container">
		<p class="float-right"><a href="#">Back To Top</a></p>
		<p>© 2017 WynShop, Inc.</p>
	</footer> -->

</body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6 offset-md-3">
  <form >
  <div class="form-group">
    <%= form.text_field :name, id: :product_name, placeholder: "Product Name", class: "form-control" %>
  </div>
    <div class="form-group">
    <%= form.text_field :image, id: :image_url, placeholder: "Add Image URL", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.text_area :description, id: :product_description, placeholder: "Enter Description", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.number_field :price_in_cents, id: :product_price_in_cents, placeholder: "Enter Price In Cents", class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
  </form>
  </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/home.html.erb
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1" class=""></li>
          <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="https://ez.no/var/ezflow_site/storage/images/media/images/hackathon-landing-page-2/657157-2-eng-GB/Hackathon-landing-page-2.png" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <p><a class="btn btn-lg btn-light" href="<%= products_path %>" role="button">Shop Now</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="https://pbs.twimg.com/media/DKSHBoDW4AIk8j6.jpg" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <p><a class="btn btn-lg btn-light" href="<%= '/login' %>" role="button">Login</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="https://www.aiche.org/sites/default/files/styles/aiche_content/public/images/overview_page/Members_only_ssk_574_125898974.jpg" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <p><a class="btn btn-lg btn-light" href="<%= '/signup' %>" role="button">Sign Up</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <div class="mobile-banner pb-5">
        <img class="first-slide" src="https://ez.no/var/ezflow_site/storage/images/media/images/hackathon-landing-page-2/657157-2-eng-GB/Hackathon-landing-page-2.png" alt="First slide">
          <div class="mobile-banner-caption">
            <p><a class="btn btn-lg btn-light" href="<%= products_path %>" role="button">Shop Now</a></p>
        </div>
      </div>
      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">

        <!-- Three columns of text below the carousel -->

        <div class="center">
          <h1>Everything you need to code.</h1>
        </div>

        <div class="row">
          <% @products.each do |product| %>
            <div class="col-lg-4">
             <%= image_tag product.image, size: 140 %>
              <h2><%= product.name%></h2>
              <p><%= product.description %></p>
              <p><%= link_to "Product Details", product_path(product), class: "btn btn-primary" %></p>
            </div><!-- /.col-lg-4 -->
            <% end %>
        </div><!-- /.row -->

        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">The best laptops.</h2>
            <h2><span class="text-muted">Incredibly fast and lightweight.</span></h2>
            <p class="lead">Apple MacBooks (Air / Pro) are preferred for Wyncode.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="https://multimedia.bbycastatic.ca/multimedia/products/500x500/103/10360/10360535.jpg" data-holder-rendered="true">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">The best backpacks.</h2>
            <h2><span class="text-muted">Stylish and practical.</span></h2>
            <p class="lead">Herschel and JanSport leave the competition in the dust.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="https://cdn1.ebags.com/is/image/im4/342844_1_1?resmode=4&op_usm=1,1,1,&qlt=70,1&hei=500&wid=500&align=0,1" data-holder-rendered="true">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">The best cold gear.</h2>
            <h2><span class="text-muted">Zuckerberg approved.</span></h2>
            <p class="lead">Completely necessary. Trust us.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="500x500" src="https://i.pinimg.com/736x/fe/92/9a/fe929a42a9ef78037b6f1a18beada3d2--minimalist-closet-travel-style.jpg" data-holder-rendered="true">
          </div>
        </div>

        <!-- /END THE FEATURETTES -->

        <hr class="featurette-divider">

      	<footer class="container">
      		<p class="float-right"><a href="#">Back To Top</a></p>
      		<p>© 2017 WynShop, Inc.</p>
      	</footer>

      </div><!-- /.container -->

app/views/products/index.html.erb
<div class="text-center">
  <h1>Product List</h1>
</div>

<div class="row">
  <% @products.each do |product| %>
  <div class="col-md-4">

    <div class="card">
      <div class="card-body">
        <%= image_tag product.image, :size => "100%", :crop => :fill %>
        <h4 class="card-title"><%= product.name %></h4>
        <p class="card-text"><%= product.description %></p>
        <p class="card-text"><strong>$ <%= product.formatted_price %></strong></p>
        <button class="btn btn-primary"><%= link_to 'View', product %></button>

          <% if current_user && current_user.is_admin   %>
          <div class="admin">
            <button type="button" class="btn btn-warning">
              <%= link_to 'Edit', edit_product_path(product) %>
            </button>
            <button type="button" class="btn btn-danger">
              <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            </button>

          </div>
         <% end %>

      </div>
    </div>
  </div>
  <% end %>
</div>

<div class="new-product">

    <% if current_user && current_user.is_admin %>
    <button type="button" class="btn btn-success"><%= link_to 'New Product', new_product_path %></button>
    <% end %>

</div>
<hr class="featurette-divider">

<footer class="container">
  <p class="float-right"><a href="#">Back To Top</a></p>
  <p>© 2017 WynShop, Inc.</p>
</footer>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice" class="my-4"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<div class="row">
<div class="col-md-6">
  <div class="product-full-image"><%= image_tag @product.image %></div>
</div>
<div class="col-md-6">
  <div class="title">
  <h1><%= @product.name %></h1>
</div>
  <div class="price">
  <strong>Price:</strong>
  <div class="amount">$ <%= @product.formatted_price %></div>
</div>
<!-- tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="desciption" aria-selected="true">Description</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="false">Reviews</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="new-review-tab" data-toggle="tab" href="#new-review" role="tab" aria-controls="new-review" aria-selected="false">Create Review</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
    <div class="product-description">
<h4 class="description-title">Description</h4>
<p>
  <%= @product.description %>
</p>
</div>
  </div>
  <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
    <h3>Reviews</h3>
<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    Added on: <%= review.created_at %>
  </p>
<% end %>
  </div>
  <div class="tab-pane fade" id="new-review" role="tabpanel" aria-labelledby="new-review-tab">
    <h3>Create a new review</h3>
<%= render 'reviews/form' %>
  </div>
</div>
<!-- end tabs -->
</div>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :review_comment %>
  </div>
 <% if @product.nil? %>
    <div class="field">
      <%= form.label :product_id %><br>
      <%= form.text_field :product_id %>
    </div>
  <% else %>
    <%= form.hidden_field :product_id, value: @product.id %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>
<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |

<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>

<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<a class="navbar-brand" href="<%= root_path %>">WynShop</a>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="<%= root_path %>">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="<%= products_path %>">Products</a>
			</li>
		</ul>
		<form class="form-inline">
			<% if current_user %>
			<p class="font-weight-bold px-4 pt-3">Hello! <%= current_user.name %></p>
			<button class="btn btn-sm btn-danger" type="button"><%= link_to "Logout", '/logout' %></button>

			<% else %>
			<button class="btn btn-sm align-middle btn-success mx-4" type="button"><%= link_to 'Login', '/login' %></button>
			<button class="btn btn-sm align-middle btn-primary" type="button"><%= link_to 'Sign Up', '/signup' %></button>
			<% end %>
		</form>
	</div>
</nav>

app/views/users/new.html.erb
<h2 class="text-center py-4">Sign Up</h2>

<%= form_for :user, :html => { :class => "col-md-6 offset-md-3" }, url: '/users' do |f| %>
<form >
  <div class="form-group">
    <%= f.text_field :name, placeholder: "Full Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :email, placeholder: "Email Address", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
  </div>
  <p class="center-align">These fields are case-sensitive</p>
  <p class="center-align"><%= f.submit "Submit", class: "btn btn-primary"%></p>
</form>
<% end %>

<!-- /*****************TEMPORARY***********************/ -->

<hr class="featurette-divider">

<footer class="container">
  <p class="float-right"></p>
  <p>© 2017 WynShop, Inc.</p>
</footer>